### ISSUE TITLE
Move multiple tabs.

### ISSUE THREAD

**Issue by mzso** [vovcacik/bug-566510-firefox-addon#2]
Hello!
Currently I can select multiple tabs but I can't move them. Is it something that's planned to be implemented?

**Comment by vovcacik** [comment]
Hi mzso,
unfortunately no. I got some work in progress, but my findings are this would require lot of nasty hacks. You might want to try [Multiple Tab Handler](https://addons.mozilla.org/addon/multiple-tab-handler/).

###### Details

Tabs dragging is controlled by couple of dragging events (e.g. dragstart, dragover, drop...). Each of the event has one or more listeners that are getting things done. The number of changes needed to support multiple tab dragging is actually quite low, however XBL inheritance does not apply on handlers, which make things complicated. For that reason I can't simply override definition of listeners; I would have to make new listeners that would handle multiselected tabs and _somehow_ make the existing listeners to support that (because they don't).

Doing all of this while retaining compatiblity with other addons, older Firefox versions and avoiding nasty hacks like code hot swapping is rather challenging.

Anyway, this feature is part of the [566510 bug](https://bugzilla.mozilla.org/show_bug.cgi?id=566510), so you it's just matter of time. Also there might be a nice simple way to do this, which I don't see at this time (if something strikes me, you will find it in this [branch](https://github.com/vovcacik/bug-566510-firefox-addon/tree/issues/2/master)).

**Comment by mzso** [comment]
Okay, then.

<blockquote>Anyway, this feature is part of the 566510 bug, so you it's just matter of time.</blockquote>

Any bug older than a year or two is unlikely to be ever dealt with. Like the notorious  <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=78414">bug78414</a>.
